// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;
const SUPABASE_KEY = SUPABASE_PUBLISHABLE_KEY ?? SUPABASE_ANON_KEY;

// Fail loudly if required env vars are missing. Vercel must set VITE_* vars.
if (!SUPABASE_URL || !SUPABASE_KEY) {
  console.error('Missing Supabase env vars. Ensure VITE_SUPABASE_URL and one of VITE_SUPABASE_PUBLISHABLE_KEY or VITE_SUPABASE_ANON_KEY are set in your environment (Vercel).');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
// TEMP DEBUG
// @ts-ignore
window.supabase = supabase
